# Generated by Django 5.1.3 on 2024-12-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandslideHistor',
            new_name='LandslideHistory',
        ),
    ]
