# Generated by Django 5.1.3 on 2024-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_management', '0002_rename_landslidehistor_landslidehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landslidehistory',
            old_name='date',
            new_name='dateOfOccurance',
        ),
        migrations.AddField(
            model_name='landslidehistory',
            name='Occured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
