# Generated by Django 5.1.3 on 2024-12-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_management', '0003_rename_date_landslidehistory_dateofoccurance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landslidehistory',
            old_name='dateOfOccurance',
            new_name='dateOfOPredictiveOccurance',
        ),
    ]
